schema.sql, src/main/java/com/part3/team07/sb01deokhugamteam07/Sb01DeokhugamTeam07Application.java, src/main/java/com/part3/team07/sb01deokhugamteam07/config/SecurityConfig.java, src/main/java/com/part3/team07/sb01deokhugamteam07/controller/UserController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/dto/user/UserDto.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/Dashboarad.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/KeyType.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/Review.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/ValueType.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/DuplicateUserEmailException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/DashboradRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/UserRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/UserService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/UserServiceTest.java
https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/5
1. 스프링 시큐리티 비활성화
어떤 변경 사항이 있나요?
=> fix: disable security

src/main/java/com/part3/team07/sb01deokhugamteam07/exception/UserExceptionHandler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/DuplicateUserEmailException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/UserService.java
https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/5
UserExceptionHandler 추가
어떤 변경 사항이 있나요?
=> feat: add User Exception Handler

src/main/java/com/part3/team07/sb01deokhugamteam07/controller/UserController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/UserExceptionHandler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/DuplicateUserEmailException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/IllegalUserPasswordException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/UserNotFoundException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/UserRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/UserService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/integration/UserServiceIntegrationTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/UserServiceTest.java
https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/10
유저 로그인 구현
잘못된 로그인 예외처리 추가
어떤 변경 사항이 있나요?
=> feat: User Login

build.gradle, src/main/java/com/part3/team07/sb01deokhugamteam07/controller/UserController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/User.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/UserExceptionHandler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/DuplicateUserEmailException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/IllegalUserPasswordException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/UserNotFoundException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/UserRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/UserService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/integration/UserServiceIntegrationTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/UserServiceTest.java
https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/13
유저 수정 기능 구현
어떤 변경 사항이 있나요?
=> feat: User Update

build.gradle, src/main/java/com/part3/team07/sb01deokhugamteam07/controller/UserController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/User.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/UserExceptionHandler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/DuplicateUserEmailException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/IllegalUserPasswordException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/UserNotFoundException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/UserRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/UserService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/integration/UserServiceIntegrationTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/UserServiceTest.java
https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/15
유저 조회 구현
어떤 변경 사항이 있나요?
=> feat: User Find

build.gradle, src/main/java/com/part3/team07/sb01deokhugamteam07/controller/UserController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/User.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/base/BaseSoftDeletableEntity.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/UserExceptionHandler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/DuplicateUserEmailException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/IllegalUserPasswordException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/UserNotFoundException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/UserRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/UserService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/integration/UserServiceIntegrationTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/UserServiceTest.java
https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/17
유저 논리적 삭제 구현
어떤 변경 사항이 있나요?
=> feat: User Logical Delete

build.gradle, src/main/java/com/part3/team07/sb01deokhugamteam07/controller/UserController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/User.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/base/BaseSoftDeletableEntity.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/UserExceptionHandler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/DuplicateUserEmailException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/IllegalUserPasswordException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/user/UserNotFoundException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/UserRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/UserService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/integration/UserServiceIntegrationTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/UserServiceTest.java
#19 
사용자 물리 삭제 구현
어떤 변경 사항이 있나요?
=> feat: User Physical Delete

README.md
#28 
테스트 커버리지 확인을 위한 Codecov 추가
어떤 변경 사항이 있나요?
=> docs: add Codecov at README.md

.github/workflows/test.yml
CI 테스트에서 application-test.yml 인식 시키기 추가
어떤 변경 사항이 있나요?
=> docs: change CI test.yml

src/main/java/com/part3/team07/sb01deokhugamteam07/controller/UserController.java
#13 
UserId NotNull 제약 조건 추가
어떤 변경 사항이 있나요?
=> refactor: add not null validate at user controller

src/main/java/com/part3/team07/sb01deokhugamteam07/config/SecurityConfig.java
#23 
인증되었음에도 불구하고  /api/users 엔드 포인트 막히는 현상 수정
어떤 변경 사항이 있나요?
=> fix: security endpoint

src/main/java/com/part3/team07/sb01deokhugamteam07/controller/UserController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/UserService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/controller/UserControllerTest.java
#46 
유저 컨트롤러 테스트 코드 추가 
어떤 변경 사항이 있나요?
=> test: user controller test

src/main/java/com/part3/team07/sb01deokhugamteam07/config/SecurityConfig.java, src/main/java/com/part3/team07/sb01deokhugamteam07/controller/UserController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/logging/MDCLoggingFilter.java, src/main/java/com/part3/team07/sb01deokhugamteam07/logging/query/IgnoreLogFilter.java, src/main/java/com/part3/team07/sb01deokhugamteam07/logging/query/LogConfiguration.java, src/main/java/com/part3/team07/sb01deokhugamteam07/logging/query/MyP6spyFormattingStrategy.java, src/main/resources/logback-spring.xml
#35 
요청 별 ID와 IP 주소를 MDC에 추가하고 로그 메시지 및 응답 헤더에 추가
어떤 변경 사항이 있나요?
=> feat: add MDC Logging filter

src/main/java/com/part3/team07/sb01deokhugamteam07/controller/BookController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/Book.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/BookService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/controller/BookControllerTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/BookServiceTest.java
#50 
도서 논리 삭제 구현
어떤 변경 사항이 있나요?
=> feat: book soft delete

src/main/java/com/part3/team07/sb01deokhugamteam07/controller/UserController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/User.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/UserService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/controller/UserControllerTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/UserServiceTest.java
#70 
유저 논리 삭제 메서드 이름 변경(softDelete())
어떤 변경 사항이 있나요?
=> refactor: change method name user soft delete

src/main/java/com/part3/team07/sb01deokhugamteam07/controller/BookController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/Book.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/BookService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/controller/BookControllerTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/BookServiceTest.java
=> feat: book hard delete

src/main/java/com/part3/team07/sb01deokhugamteam07/service/CommentService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/CommentServiceTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/ReviewServiceTest.java
#81 
- 댓글/좋아요 생성 및 삭제 시 리뷰 카운트 동기화 처리
어떤 변경 사항이 있나요?
댓글 관련 로직(create, delete)에 카운트 동기화 처리를 추가했습니다.
해당 변경사항에 맞춰 기존 테스트 코드도 보완했습니다.
혹시 로직 처리 방식이나 테스트 구조에서 개선할 점이 있으면 편하게 말씀해주세요!
=> feat: review count sync

src/main/java/com/part3/team07/sb01deokhugamteam07/batch/popularreview/PopularReviewDashboardBatchService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/controller/NotificationController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/dto/notification/NotificationDto.java, src/main/java/com/part3/team07/sb01deokhugamteam07/dto/notification/UUID.java, src/main/java/com/part3/team07/sb01deokhugamteam07/dto/notification/request/NotificationCreateRequest.java, src/main/java/com/part3/team07/sb01deokhugamteam07/dto/notification/request/NotificationType.java, src/main/java/com/part3/team07/sb01deokhugamteam07/dto/notification/request/NotificationUpdateRequest.java, src/main/java/com/part3/team07/sb01deokhugamteam07/dto/notification/response/CursorPageResponseNotificationDto.java, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/Notification.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/ErrorCode.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/notification/NotificationException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/notification/NotificationNotFoundException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/exception/notification/NotificationUnauthorizedException.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/NotificationRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/NotificationRepositoryCustom.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/NotificationRepositoryCustomImpl.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/UserRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/CommentService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/NotificationService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/ReviewService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/batch/popularreview/PopularReviewDashboardBatchServiceTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/controller/NotificationControllerTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/repository/NotificationRepositoryCustomImplTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/CommentServiceTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/NotificationServiceTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/ReviewServiceTest.java
[#89](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/89)
알림 읽음 상태 로직 구현
알림 NOT FOUND 에러 코드 추가
어떤 변경 사항이 있나요?
=> feat: notification update

src/main/java/com/part3/team07/sb01deokhugamteam07/batch/popularbook/PopularBookDashboardBatchService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/batch/popularreview/PopularReviewDashboardBatchService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/batch/poweruser/PowerUserDashboardBatchService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/DashboardService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/batch/popularbook/PopularBookDashboardBatchServiceTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/DashboardServiceTest.java
[#127](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/127)
DB 에 대시보드를 저장하는 로직에서 새벽에 진행되는 배치 작업임을 고려하여
- 커스텀 에러를 제거하고 참고할 데이터가 없을 시엔 조기 종료하도록 추가
- DataAccessException 과 일반 예외에 대한 try-catch 문 적용
대시보드 호출할 시 조기 반환하도록 설정
어떤 변경 사항이 있나요?
커스텀으로 브랜치를 열었는데 진행 과정에서 부득이하게 커스텀 예외를 제외하게 되었습니다. 그 점 감안해서 봐주십쇼 감사합니다!
=> refactor : dashboard custom exceptions

src/main/java/com/part3/team07/sb01deokhugamteam07/service/NotificationService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/controller/NotificationControllerTest.java
[#131](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/131)
- 커스텀 예외 처리 추가
- NotificaitonContorllerTest 의 요청자 ID 누락 관련 테스트 주석 처리 취소
어떤 변경 사항이 있나요?
=> refactor : notification cumtom exceptions

.github/workflows/deploy.yml, Dockerfile, ecs/task-definition.json, src/main/resources/application-prod.yml
#73 
CI/CD를 위한 GitHub Actions 워크플로우 추가
어떤 변경 사항이 있나요?
=> docs: CI/CD deploy.yml

src/main/java/com/part3/team07/sb01deokhugamteam07/exception/GlobalExceptionHandler.java
[#140](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/140)
알림 Http 상태 코드 예외 지정
어떤 변경 사항이 있나요?
=> feat: notification httpStatus

src/main/resources/application-prod.yml
=> docs: update application-prod.yml

src/main/java/com/part3/team07/sb01deokhugamteam07/config/SecurityConfig.java
=> fix: add security endpoint

Dockerfile
=> [docs] change time zone Update Dockerfile

.github/workflows/deploy.yml
=> [docs] Update deploy.yml

schema.sql, src/main/java/com/part3/team07/sb01deokhugamteam07/entity/Dashboard.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/StorageService.java
enum -> varchar로 변경
어떤 변경 사항이 있나요?
=> fix: schema에서 enum -> varchar로 변경

src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/ApplicationScheduler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/BookReviewScheduler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/NotificationService.java
=> feature: update scheduler time

src/main/java/com/part3/team07/sb01deokhugamteam07/config/SecurityConfig.java
#113 
액츄에이터 엔드포인트 추가
어떤 변경 사항이 있나요?
=> fix: add security filter /actuator/**

src/main/java/com/part3/team07/sb01deokhugamteam07/repository/DashboardRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/ReviewRepository.java
[#156](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/156)
Lazy Loading 으로 인한 프록시 참조 문제 해결을 위해 reviewRepositroy 단에 findAllById 메서드를 Override하여 @EntityGrapth 어노테이션 추가
어떤 변경 사항이 있나요?
=> fix: popular reviews proxy problem

src/main/java/com/part3/team07/sb01deokhugamteam07/controller/BookController.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/BookRepositoryCustomImpl.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/BookService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/BookServiceTest.java
#157 
- book findAll 디폴트 값 변경
어떤 변경 사항이 있나요?
=> fix: book findAll fix

src/main/java/com/part3/team07/sb01deokhugamteam07/service/NotificationService.java
[#155](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/155)
CursorPageResponseNotificationDto totalElements 누락 제거
어떤 변경 사항이 있나요?
=> fix: notification-find-fix

src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/ApplicationScheduler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/BookReviewScheduler.java
도서 관련 스케줄링, 알림 삭제 시간 복귀'
테스트를 위해 연산 기능 시각 17시로 지정
어떤 변경 사항이 있나요?
=> feature : update scheduler time

src/main/java/com/part3/team07/sb01deokhugamteam07/repository/ReviewRepositoryImpl.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/ReviewService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/ReviewServiceTest.java
#161 
- ReviewService.findAll()의 커서 기반 페이지네이션 테스트 보완
- 정렬 기준이 CREATED_AT일 경우, 커서 값으로 createdAt을 사용하는 로직으로 수정
어떤 변경 사항이 있나요?
=> fix: review findAll paging

src/main/java/com/part3/team07/sb01deokhugamteam07/repository/DashboardRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/ApplicationScheduler.java
[#165](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/165)
DashboardRepository 네이티브 쿼리 수정
어떤 변경 사항이 있나요?
=> fix: dashboard repository native query

src/main/java/com/part3/team07/sb01deokhugamteam07/repository/ReviewRepositoryCustom.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/ReviewRepositoryImpl.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/ReviewService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/repository/ReviewRepositoryTest.java
#169 
- 리뷰 목록 조회 시, count 값 추가
어떤 변경 사항이 있나요?
=> fix: review findAll count

src/main/java/com/part3/team07/sb01deokhugamteam07/dto/book/PopularBookDto.java, src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/ApplicationScheduler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/DashboardService.java
[#170](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/170)
스케줄링 작업 전 대시보드 데이터 전체 삭제 기능
어떤 변경 사항이 있나요?
일차적으로 로컬에서 데이터 삭제 후 스케줄링 작업 하는 것 완료했습니다!
=> feature : dashboard delete data

src/main/java/com/part3/team07/sb01deokhugamteam07/dto/book/PopularBookDto.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/DashboardRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/ApplicationScheduler.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/DashboardService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/NotificationService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/ReviewService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/DashboardServiceTest.java
[#175](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/175)
좋아요를 눌렀을 때, 상대의 알림에 좋아요 문구가 아닌 댓글이 뜨는 현상 해결
순위 달성시 알림 생성 불가 현상 해결
어떤 변경 사항이 있나요?
=> fix : notification bug fix

.github/workflows/test.yml
=> docs: Update test.yml

src/main/java/com/part3/team07/sb01deokhugamteam07/repository/ReviewRepositoryCustom.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/ReviewRepositoryImpl.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/ReviewService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/repository/ReviewRepositoryTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/ReviewServiceTest.java
#178 
- 반환 타입을 Tuple → DTO로 변환하여 서비스 레이어에서 QueryDSL 의존 제거
- ASC 방향 정렬 시 누락되던 보조 정렬(createdAt) 추가
어떤 변경 사항이 있나요?
=> refactor: review findAll

src/main/java/com/part3/team07/sb01deokhugamteam07/config/SecurityConfig.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/BookRepositoryCustomImpl.java, src/main/java/com/part3/team07/sb01deokhugamteam07/storage/LocalStorage.java, src/main/java/com/part3/team07/sb01deokhugamteam07/util/TitleNormalizer.java, src/test/java/com/part3/team07/sb01deokhugamteam07/repository/BookRepositoryTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/repository/CommentRepositoryCustomImplTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/repository/DashboardRepositoryCustomImplTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/repository/LikeRepositoryTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/repository/NotificationRepositoryCustomImplTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/repository/NotificationRepositoryTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/repository/ReviewRepositoryTest.java
#157 
- 도서 타이틀로 정렬 시 공백, 특수문자 무시
- PostgreSQL 전용 문법 사용으로 인해 운영, 테스트 환경 코드 분기
어떤 변경 사항이 있나요?
=> refactor: book find all fix

src/main/java/com/part3/team07/sb01deokhugamteam07/service/StorageService.java
#184 
- 도서 썸네일 url 잘못된 경로로 지정되는 버그 픽스
어떤 변경 사항이 있나요?
=> fix: book thumbnail url

src/main/java/com/part3/team07/sb01deokhugamteam07/batch/DateRangeUtil.java, src/main/java/com/part3/team07/sb01deokhugamteam07/batch/popularbook/PopularBookDashboardBatchService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/batch/popularreview/PopularReviewDashboardBatchService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/batch/poweruser/PowerUserDashboardBatchService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/ApplicationScheduler.java, src/test/java/com/part3/team07/sb01deokhugamteam07/batch/DateRangeUtilTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/batch/popularbook/PopularBookDashboardBatchServiceTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/batch/popularreview/PopularReviewDashboardBatchServiceTest.java, src/test/java/com/part3/team07/sb01deokhugamteam07/batch/poweruser/PowerUserDashboardBatchServiceTest.java
[#185
](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/185)
일간: 현재 시각 기준 24시간
주간: 오늘 포함 이전 7일
어떤 변경 사항이 있나요?
=> refactor : dashboard date logic

src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/ApplicationScheduler.java
대시보드 테스트를 위한 시각 변경
어떤 변경 사항이 있나요?
=> chore: adjust scheduler for test

src/main/java/com/part3/team07/sb01deokhugamteam07/repository/BookRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/repository/ReviewRepository.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/BookService.java, src/test/java/com/part3/team07/sb01deokhugamteam07/service/BookServiceTest.java
#191 
- 논리 삭제된 도서 조회 안 되게 수정
어떤 변경 사항이 있나요?
=> refactor: book query

src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/ApplicationScheduler.java
chore/adjust-scheduler-for-test
- 매 시각 5분(대시보드 데이터 삭제), 6분(대시보드 데이터 생성)에 시작
- 
어떤 변경 사항이 있나요?
=> chore: 대시보드 테스트를 위해 매시각으로 변경

ecs/task-definition.json
#199 
- ocr key 인증 방식 변경
어떤 변경 사항이 있나요?
=> feat: book ocr

ecs/task-definition.json
#199 
- 잘못된 경로 수정
어떤 변경 사항이 있나요?
=> fix: task-definition.json modify

ecs/task-definition.json
#199 
- task-definition.json에 environment 설정 추가
어떤 변경 사항이 있나요?
=> chore: modify environment

build.gradle, src/main/java/com/part3/team07/sb01deokhugamteam07/config/OcrConfig.java
#199 
- OcrConfig에서 수동으로 ImageAnnotatorClient 설정
어떤 변경 사항이 있나요?
=> refactor: OcrConfig modify

ecs/task-definition.json
#199 
- ocr-key.json을 실행 시 파일에 작성
어떤 변경 사항이 있나요?
=> chore: ocr-key.json write

build.gradle
build.gradle에서 p6spy, jwt 의존성 제거
어떤 변경 사항이 있나요?
=> docs: remove p6spy dependency at build.gradle

ecs/task-definition.json
#199 
- task-deficition.json 환경에 옵션 추가
어떤 변경 사항이 있나요?
=> fix: task-deficition modify

src/main/java/com/part3/team07/sb01deokhugamteam07/batch/popularreview/PopularReviewDashboardBatchService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/CommentService.java, src/main/java/com/part3/team07/sb01deokhugamteam07/service/ReviewService.java
[#211](https://github.com/SB01-Team07/sb01-deokhugam-team07/issues/211)
이슈 내용: 댓글, 좋아요, 10위 진출 알림 생성을 알리는 로그 추가
어떤 변경 사항이 있나요?
=> chore: log alert events

ecs/task-definition.json
=> docs: Update task-definition.json

src/main/java/com/part3/team07/sb01deokhugamteam07/scheduler/ApplicationScheduler.java
chore/adjust-scheduler-for-test
대시보드 연산 시각 매시각에서 하루에 한 번으로 변경
어떤 변경 사항이 있나요?
=> chore: adjust scheduler
